#!/bin/python3
print('hi I\'m Lina and I\'m currently learning how to use python')
print ('and this is the cat which I don\'t have right now')
print('''
              .__....._             _.....__,
                 .": o :':         ;': o :".
                 `. `-' .'.       .'. `-' .'   
                   `---'             `---'  

         _...----...      ...   ...      ...----..._
      .-'__..-""'----    `.  `"`  .'    ----'""-..__`-.
     '.-'   _.--"""'       `-._.-'       '"""--._   `-.`
     '  .-"'                  :                  `"-.  `
       '   `.              _.'"'._              .'   `
             `.       ,.-'"       "'-.,       .'
               `.                           .'
                 `-._                   _.-'
                     `"'--...___...--'"`
''')
born = input('One quick question before you go: What year were you born?')
born = int(born)
age = 2025 - (born)
print('Great!In the year 2025 you\'ll be', age,'years old!')
dogage = input('However, do you want to know your age in dog years')
if dogage == 'yes':
  currentage = input('Write your current age:')
  currentage = int(currentage)
  dog = (currentage) * 7
  print ('You are', dog,'in dog years!')
elif dogage == 'no':
  print ('Sorry, bye!')
  

